### ISSUE TITLE
'Admin cli volume ls' command fails if it is executed while volume removal is in progress.

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1072]
Test Steps:

1. Created 500 volumes of 100 mb each sequentially. 
2. After all volumes were created, did docker volume ls.
3. Then did admin cli volume ls.
4. Next removed all the volumes using command ```docker volume rm $(docker volume ls)```. 
While the volumes are being removed, did ```admin cli volume ls``` - command output shows stack trace as well as volumes.

Snippet from command output is as follows:
```
Arguments: ('/vmfs/volumes/sharedVmfs-0/dockvols/11111111-1111-1111-1111-111111111111/dockerVol_4jK6B.vmdk',)
--- Logging error ---
Traceback (most recent call last):
  File "/build/mts/release/bora-4564106/bora/build/esx/release/vmvisor/sys-boot/lib64/python3.5/logging/handlers.py", line 71, in emit
  File "/build/mts/release/bora-4564106/bora/build/esx/release/vmvisor/sys-boot/lib64/python3.5/logging/handlers.py", line 187, in shouldRollover
  File "/build/mts/release/bora-4564106/bora/build/esx/release/vmvisor/sys-boot/lib64/python3.5/logging/__init__.py", line 830, in format
  File "/build/mts/release/bora-4564106/bora/build/esx/release/vmvisor/sys-boot/lib64/python3.5/logging/__init__.py", line 567, in format
  File "/build/mts/release/bora-4564106/bora/build/esx/release/vmvisor/sys-boot/lib64/python3.5/logging/__init__.py", line 330, in getMessage
TypeError: %x format: an integer is required, not str
Call stack:
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 1038, in <module>
    main()
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 53, in main
    args.func(args)
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 522, in ls
    rows = generate_ls_rows(tenant_reg)
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 561, in generate_ls_rows
    size_info = get_vmdk_size_info(path)
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 651, in get_vmdk_size_info
    vol_info = kv.get_vol_info(path)
  File "/usr/lib/vmware/vmdkops/bin/volume_kv.py", line 174, in get_vol_info
    return kvESX.get_info(vol_path)
  File "/usr/lib/vmware/vmdkops/Python/threadutils.py", line 82, in protected
    return func(*args, **kwargs)
  File "/usr/lib/vmware/vmdkops/Python/kvESX.py", line 324, in get_info
    logging.warning("Failed to open disk - %x", volpath)
  File "/build/mts/release/bora-4564106/bora/build/esx/release/vmvisor/sys-boot/lib64/python3.5/logging/__init__.py", line 1823, in warning
  File "/build/mts/release/bora-4564106/bora/build/esx/release/vmvisor/sys-boot/lib64/python3.5/logging/__init__.py", line 1291, in warning
  File "/build/mts/release/bora-4564106/bora/build/esx/release/vmvisor/sys-boot/lib64/python3.5/logging/__init__.py", line 1415, in _log
  File "/build/mts/release/bora-4564106/bora/build/esx/release/vmvisor/sys-boot/lib64/python3.5/logging/__init__.py", line 1425, in handle
  File "/build/mts/release/bora-4564106/bora/build/esx/release/vmvisor/sys-boot/lib64/python3.5/logging/__init__.py", line 1487, in callHandlers
  File "/build/mts/release/bora-4564106/bora/build/esx/release/vmvisor/sys-boot/lib64/python3.5/logging/__init__.py", line 855, in handle
  File "/build/mts/release/bora-4564106/bora/build/esx/release/vmvisor/sys-boot/lib64/python3.5/logging/handlers.py", line 75, in emit
Message: 'Failed to open disk - %x'
Arguments: ('/vmfs/volumes/sharedVmfs-0/dockvols/11111111-1111-1111-1111-111111111111/dockerVol_7b1a3.vmdk',)
Volume           Datastore     VM-Group  Capacity  Used  Filesystem  Policy  Disk Format  Attached-to  Access      Attach-as               Created By      Created Date
---------------  ------------  --------  --------  ----  ----------  ------  -----------  -----------  ----------  ----------------------  --------------  ------------------------
dockerVol_xl82d  sharedVmfs-0  _DEFAULT  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  Photon-Dker-11  Thu Mar 23 18:33:13 2017
dockerVol_1vt4a  sharedVmfs-0  _DEFAULT  N/A       N/A   N/A         N/A     N/A          detached     read-write  independent_persistent  N/A             N/A
dockerVol_nJvNm  sharedVmfs-0  _DEFAULT  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  Photon-Dker-11  Thu Mar 23 18:33:22 2017
dockerVol_uLcRf  sharedVmfs-0  _DEFAULT  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  Photon-Dker-11  Thu Mar 23 18:33:25 2017
dockerVol_9zzCY  sharedVmfs-0  _DEFAULT  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  Photon-Dker-11  Thu Mar 23 18:33:27 2017
dockerVol_Rw5Ba  sharedVmfs-0  _DEFAULT  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  Photon-Dker-11  Thu Mar 23 18:33:30 2017
dockerVol_zE7C5  sharedVmfs-0  _DEFAULT  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  Photon-Dker-11  Thu Mar 23 18:33:33 2017
dockerVol_lFGRz  sharedVmfs-0  _DEFAULT  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  Photon-Dker-11  Thu Mar 23 18:33:36 2017
dockerVol_alyNw  sharedVmfs-0  _DEFAULT  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  Photon-Dker-11  Thu Mar 23 18:33:39 2017
dockerVol_GFVaH  sharedVmfs-0  _DEFAULT  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  Photon-Dker-11  Thu Mar 23 18:33:42 2017
dockerVol_9KGy7  sharedVmfs-0  _DEFAULT  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  Photon-Dker-11  Thu Mar 23 18:33:45 2017
dockerVol_3Qa9O  sharedVmfs-0  _DEFAULT  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  Photon-Dker-11  Thu Mar 23 18:33:48 2017
dockerVol_2I9qb  sharedVmfs-0  _DEFAULT  N/A       N/A   N/A         N/A     N/A          detached     read-write  independent_persistent  N/A             N/A
dockerVol_OoEPH  sharedVmfs-0  _DEFAULT  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  Photon-Dker-11  Thu Mar 23 18:33:54 2017
dockerVol_Y9T3N  sharedVmfs-0  _DEFAULT  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  Photon-Dker-11  Thu Mar 23 18:33:57 2017
dockerVol_ykqGU  sharedVmfs-0  _DEFAULT  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  Photon-Dker-11  Thu Mar 23 18:34:00 2017
dockerVol_cSC3x  sharedVmfs-0  _DEFAULT  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  Photon-Dker-11  Thu Mar 23 18:34:03 2017
dockerVol_1oxw9  sharedVmfs-0  _DEFAULT  N/A       N/A   N/A         N/A     N/A          detached     read-write  independent_persistent  N/A             N/A
dockerVol_WPu6m  sharedVmfs-0  _DEFAULT  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  Photon-Dker-11  Thu Mar 23 18:34:09 2017

```

Setup:

```
4 ESXs - 364 VMs - 4 shared Vmfs datastores
Each shared vmfs has ~90 VMs.
All the VMs are powered-on.

```

Logs:
[docker-volume-vsphere.txt](https://github.com/vmware/docker-volume-vsphere/files/865995/docker-volume-vsphere.txt)
[vmdk_ops.log.1.txt](https://github.com/vmware/docker-volume-vsphere/files/865996/vmdk_ops.log.1.txt)
[vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/865997/vmdk_ops.txt)

**Comment by shaominchen** [comment]
The fix is trivial: just replace %x with %s at line 324 in the file esx_service/utils/kvESX.py
