### ISSUE TITLE
[Multi-ESX] admin cli vm-group access ls command fails with default configuration

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1123]
- No configuration is set on the esx:

```
[root@sc-rdops-vm04-dhcp-106-152:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group create --name=tenant1
Internal Error(Error: Please init configuration in vmdkops_admin before trying to change it)

```
- Only have _DEFAULT tenant on the ESX
```
[root@sc-rdops-vm04-dhcp-106-152:~] usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group ls
Uuid                                  Name      Description                 Default_datastore  VM_list
------------------------------------  --------  --------------------------  -----------------  -------
11111111-1111-1111-1111-111111111111  _DEFAULT  This is a default vm-group

```
- Try running ```admin cli vm-group access ls``` command but see error stacktrace.

```
[root@sc-rdops-vm04-dhcp-106-152:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group access ls --name=_DEFAULT
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 1356, in <module>
    main()
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 58, in main
    args.func(args)
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 1121, in tenant_access_ls
    rows = generate_tenant_access_ls_rows(privileges)
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 1100, in generate_tenant_access_ls_rows
    if not p.datastore_url or p.datastore_url == auth_data_const.DEFAULT_DS_URL:
AttributeError: 'dict' object has no attribute 'datastore_url'
[root@sc-rdops-vm04-dhcp-106-152:~]

```

**Comment by ashahi1** [comment]
Three more instances - trying to update the "Description", "Name" and "--default-datastore" fields for the _DEFAULT tenant but see stacktrace for each command.

No configuration is set on the ESX.

-----------------------------------

Steps and their output are as follows:

- Trying to update description for the _DEFAULT tenant:
```

[root@sc-rdops-vm04-dhcp-106-152:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group update --name=_DEFAULT --description="New description of default tenant"
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 1356, in <module>
    main()
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 58, in main
    args.func(args)
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 947, in tenant_update
    default_datastore=args.default_datastore)
  File "/usr/lib/vmware/vmdkops/Python/auth_api.py", line 379, in _tenant_update
    error_msg = tenant.set_description(auth_mgr.conn, description)
  File "/usr/lib/vmware/vmdkops/Python/auth_data.py", line 288, in set_description
    conn.execute(
AttributeError: 'NoneType' object has no attribute 'execute'
[root@sc-rdops-vm04-dhcp-106-152:~]

```

- Trying to update name field for the _DEFAULT tenant:
```
[root@sc-rdops-vm04-dhcp-106-152:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group update --name=_DEFAULT --new-name=new-vm-group1
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 1356, in <module>
    main()
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 58, in main
    args.func(args)
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 950, in tenant_update
    return operation_fail(error_info.msg)
AttributeError: 'tuple' object has no attribute 'msg'
[root@sc-rdops-vm04-dhcp-106-152:~]

```

- Trying to update --default-datastore for the _DEFAULT tenant:

```
[root@sc-rdops-vm04-dhcp-106-152:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group update --name=_DEFAULT --default-datastore=sharedVmfs-0
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 1356, in <module>
    main()
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 58, in main
    args.func(args)
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 947, in tenant_update
    default_datastore=args.default_datastore)
  File "/usr/lib/vmware/vmdkops/Python/auth_api.py", line 389, in _tenant_update
    error_msg= tenant.set_default_datastore(auth_mgr.conn, datastore_url)
  File "/usr/lib/vmware/vmdkops/Python/auth_data.py", line 304, in set_default_datastore
    conn.execute(
AttributeError: 'NoneType' object has no attribute 'execute'
[root@sc-rdops-vm04-dhcp-106-152:~]

```

**Comment by ashahi1** [comment]
DB mode is NotConfigured
```
=== Authorization Config DB:
DB_Mode: NotConfigured (no local DB, no symlink to shared DB)
DB_LocalPath: N/A
DB_SharedLocation: N/A
```
- Trying to add --default-datastore for _DEFAULT tenant 
```
[root@sc-rdops-vm06-dhcp-162-163:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group access add --name=_DEFAULT
--datastore=vsanDatastore  --allow-create --default-datastore --volume-maxsize=800MB --volume-totalsize=100GB
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 1356, in <module>
    main()
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 58, in main
    args.func(args)
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 1055, in tenant_access_add
    volume_totalsize_in_MB=volume_totalsize_in_MB
  File "/usr/lib/vmware/vmdkops/Python/auth_api.py", line 683, in _tenant_access_add
    if privilege_exist(existing_privileges, datastore_url):
  File "/usr/lib/vmware/vmdkops/Python/auth_api.py", line 634, in privilege_exist
    if datastore_url == p.datastore_url:
AttributeError: 'dict' object has no attribute 'datastore_url'
[root@sc-rdops-vm06-dhcp-162-163:~]

```

**Comment by shuklanirdesh82** [comment]
keeping this as P0 due to regression ... 

@pshahzeb I am parking with you.

**Comment by msterin** [comment]
related to #1065

**Comment by ashahi1** [comment]
- DB_Mode: NotConfigured 
```
=== Authorization Config DB:
DB_LocalPath: N/A
DB_SharedLocation: N/A
DB_Mode: NotConfigured (no local DB, no symlink to shared DB)
[root@sc-rdops-vm06-dhcp-187-200:~]

```

- Trying to add a vm to the tenant
```
[root@sc-rdops-vm06-dhcp-187-200:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group vm add --name=tenant-t1 --vm-list=photon-VM0.2
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 1356, in <module>
    main()
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 58, in main
    args.func(args)
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 982, in tenant_vm_add
    error_info = auth_api._tenant_vm_add(args.name, args.vm_list)
  File "/usr/lib/vmware/vmdkops/Python/auth_api.py", line 478, in _tenant_vm_add
    error_info, tenant = get_tenant_from_db(name)
  File "/usr/lib/vmware/vmdkops/Python/auth_api.py", line 58, in get_tenant_from_db
    error_info = error_code.generate_error_info(error_msg)
  File "/usr/lib/vmware/vmdkops/Python/error_code.py", line 116, in generate_error_info
    fmstr = error_code_to_message[err_code]
KeyError: 'Error: Please init configuration in vmdkops_admin before trying to change it'
[root@sc-rdops-vm06-dhcp-187-200:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py status

```

**Comment by msterin** [comment]
@pshahzeb - FYI , I've fixed some of this and will submit a PR tonight. Not all though :-). Please stand by
