### ISSUE TITLE
Change vmdk_utils.py:get_vm_config_path() to use the same code in executeRequestThread() to fetch VM config path.

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#1161]
vmdk_ops.py:executeRequestThread() uses the VSISH node to figure the VM config path which gets the datastore_URL as a UUID. And hence immune to datastore path names with spaces in it. 

vmdk_utils.py:get_vm_config_path()  is doing the same but via the VM object which returns the datastore name. And trying to split the value returned returns error if the datastore name has spaces in it:

ERROR: test_vmdkops_on_default_tenant_vm (__main__.VmdkTenantTestCase)
Test vmdk life cycle on a VM which belongs to DEFAULT tenant

Traceback (most recent call last):
  File "/tmp/vmdk_ops_unittest/vmdk_ops_test.py", line 791, in setUp
    self.vm1_config_path = vmdk_utils.get_vm_config_path(self.vm1_name)
  File "/usr/lib/vmware/vmdkops/Python/vmdk_utils.py", line 308, in get_vm_config_path
    datastore, path = config_path.split()
ValueError: too many values to unpack

This is because VM path is like this - "/vmfs/volumes/bigone (1)". The function get_vm_config_path() is used only for test code and for datastore names with spaces, hence not observed till date.

Suggest moving the code used in executeRequestThread() into vmdk_utils.get_vm_config_path() and use that in both the service and test code.

**Comment by govint** [comment]
Code issue and nothing's broken really.
