### ISSUE TITLE
Addition of VM to VM Group fails

### ISSUE THREAD

**Issue by venilnoronha** [vmware/docker-volume-vsphere#1281]
I came across this issue while trying out the multi-tenancy feature.

### Issue
```
[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup create --name=Product1Dev --default-datastore=datastore1
vmgroup 'Product1Dev' is created. Do not forget to run 'vmgroup vm add' to add vm to vmgroup.

[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup vm add --vm-list=ubu-vm-1 --name=Product1Dev
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 1414, in <module>
    main()
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 61, in main
    args.func(args)
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 999, in tenant_vm_add
    return operation_fail(error_info.msg)
```

### Version
```
[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py status
=== Service: 
Version: 0.14.0577889-0.0.1
Status: Running
Pid: 43891
Port: 1019
LogConfigFile: /etc/vmware/vmdkops/log_config.json
LogFile: /var/log/vmware/vmdk_ops.log
LogLevel: INFO
=== Authorization Config DB: 
DB_LocalPath: /etc/vmware/vmdkops/auth-db
DB_SharedLocation: N/A
DB_Mode: SingleNode (local DB exists)
```

**Comment by venilnoronha** [comment]
I don't see this issue anymore.

```
[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py config init --local
Warning: this feature is EXPERIMENTAL
Creating new DB at /etc/vmware/vmdkops/auth-db
[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup create --name=Product1Dev --default-datastore=datastore1
vmgroup 'Product1Dev' is created. Do not forget to run 'vmgroup vm add' to add vm to vmgroup.
[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup vm add --vm-list=ubu-vm-1 --name=Product1Dev
vmgroup vm add succeeded
```

**Comment by tusharnt** [comment]
Venil,
If this was happening due to a setup issue then please close the issue. If not, we need to analyze the further to find the root cause.

**Comment by venilnoronha** [comment]
It probably must have occurred due to the setup. Closing.
