### ISSUE TITLE
Unhandled exception in case of invalid volume option size literals

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1375]
CI : https://ci.vmware.run/vmware/docker-volume-vsphere/411

```
{"Name":"option_volume_26222426471854123","Opts":{"fstype":"ext4","size":"100gbEE"}},"version":"2"}')
06/08/17 06:31:45 74553 [Thread-90] [ERROR  ] Unhandled Exception:
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1596, in execRequestThread
    opts=opts)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 899, in executeRequest
    error_info = authorize_check(vm_uuid, datastore_url, cmd, opts, use_default_ds, datastore, vm_datastore)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 809, in authorize_check
    error_info, tenant_uuid, tenant_name = auth.authorize(vm_uuid, datastore_url, cmd, opts)
  File "/usr/lib/vmware/vmdkops/Python/auth.py", line 454, in authorize
    result = check_privileges_for_command(cmd, opts, tenant_uuid, datastore_url, privileges)
  File "/usr/lib/vmware/vmdkops/Python/auth.py", line 342, in check_privileges_for_command
    if not check_max_volume_size(opts, privileges):
  File "/usr/lib/vmware/vmdkops/Python/auth.py", line 258, in check_max_volume_size
    vol_size_in_MB = convert.convert_to_MB(get_vol_size(opts))
  File "/usr/lib/vmware/vmdkops/Python/convert.py", line 27, in convert_to_MB
    value = int(vol_size_str[:-2])
ValueError: invalid literal for int() with base 10: '100GB'
```

**Comment by govint** [comment]
Fixed via #1383
