### ISSUE TITLE
Command to set max-volume-size for vmgroup fails if size is specified as string 

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1409]
**Steps:**
1. Setup only had _DEFAULT tenant.
2. Set --volume-maxsize for _DEFAULT tenant to 2GB
3. Then tried to revert the --volume-maxsize to the way it was - revert it back to Unset. 
Basically I again wanted to make  volume-maxsize as unlimited for _DEFAULT tenant - Failed.

Ideally, we shouldn't see a stack trace if a particular command fails.

===================

Steps and their output are as follows:

1. Setup only had _DEFAULT tenant.
```
[root@sc-rdops-vm04-dhcp-100-33:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup access ls --name=_DEFAULT
Datastore  Allow_create  Max_volume_size  Total_size
---------  ------------  ---------------  ----------
_ALL_DS    True          Unset            Unset
_VM_DS     True          Unset            Unset

[root@sc-rdops-vm04-dhcp-100-33:~]
```
2. Set --volume-maxsize for _DEFAULT tenant to 2GB
```
[root@sc-rdops-vm04-dhcp-100-33:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup access set --name=_DEFAULT --datastore=_VM_DS --allow-create=True --volume-maxsize=2GB
vmgroup access set succeeded
[root@sc-rdops-vm04-dhcp-100-33:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup access ls --name=_DEFAULT
Datastore  Allow_create  Max_volume_size  Total_size
---------  ------------  ---------------  ----------
_ALL_DS    True          Unset            Unset
_VM_DS     True          2.00GB           Unset

[root@sc-rdops-vm04-dhcp-100-33:~]
```
3. Tried to revert the --volume-maxsize to the way it was - revert it back to Unset.
```
[root@sc-rdops-vm04-dhcp-100-33:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup access set --name=_DEFAULT --datastore=_VM_DS --allow-create=True --volume-maxsize=Unset
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 1406, in <module>
    main()
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 61, in main
    args.func(args)
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 1083, in tenant_access_set
    volume_maxsize_in_MB = convert.convert_to_MB(args.volume_maxsize)
  File "/usr/lib/vmware/vmdkops/Python/convert.py", line 27, in convert_to_MB
    value = int(vol_size_str[:-2])
ValueError: invalid literal for int() with base 10: 'Uns'
[root@sc-rdops-vm04-dhcp-100-33:~]

```

**Comment by govint** [comment]
Setting mustfix because this is causing a code exception for user input which has to be fixed.

**Comment by govint** [comment]
This issue was fixed via https://github.com/vmware/docker-volume-vsphere/pull/1383 a day after this issue was filed :-). Closing
