### ISSUE TITLE
vsan_info_test.py test under test-esx target fails

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1913]
Steps:
1. Ran ```make test-esx``` target

vsan_info_test.py failed - Error: "Failed to create volume: Invalid datastore format 'vsandatastore'."

Testbed had a vsan datastore named: vsanDatastore

```
Running unit tests in /tmp/vmdk_ops_unittest18218/vsan_info_test.py...
FF
======================================================================
FAIL: test_ds (__main__.TestVsanInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/vmdk_ops_unittest18218/vsan_info_test.py", line 55, in setUp
    self.assertEqual(err, None, err)
AssertionError: {'Error': "Failed to create volume: Invalid datastore format 'vsandatastore'."} != None : {'Error': "Failed to create volume: Invalid datastore format 'vsandatastore'."}

======================================================================
FAIL: test_policy (__main__.TestVsanInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/vmdk_ops_unittest18218/vsan_info_test.py", line 55, in setUp
    self.assertEqual(err, None, err)
AssertionError: {'Error': "Failed to create volume: Invalid datastore format 'vsandatastore'."} != None : {'Error': "Failed to create volume: Invalid datastore format 'vsandatastore'."}

----------------------------------------------------------------------
Ran 2 tests in 0.067s

FAILED (failures=2)
Running unit tests in /tmp/vmdk_ops_unittest18218/vsan_policy_test.py...
...INFO:Delete_nonexistent_policy:
This is a negative test to delete a non-existent vsan policy.
Test is expected to raise exception log - Failed to remove the policy file error.

ERROR:root:Failed to remove test_policy policy file
Traceback (most recent call last):
  File "/tmp/vmdk_ops_unittest18218/vsan_policy.py", line 208, in delete
    os.remove(policy_path(name))
FileNotFoundError: [Errno 2] No such file or directory: '/vmfs/volumes/vsanDatastore/dockvols/policies/test_policy'
..
----------------------------------------------------------------------
Ran 5 tests in 1.604s

```

**Comment by shuklanirdesh82** [comment]
Adding mustfix to fix/improve unit test

**Comment by shuklanirdesh82** [comment]
duplicate to #1696
