### ISSUE TITLE
Not able to initialize MultiNode config DB when dockvols directory is not present 

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1930]
Not able to initialize MultiNode config DB when dockvols directory is not present 

vDVS driver version
```
[root@sc-rdops-vm17-dhcp-15-182:~] esxcli storage guestvol status
=== Service: 
Version: 0.17.c2aef31-0.0.1
Status: Running
Pid: 97781
Port: 1019
LogConfigFile: /etc/vmware/vmdkops/log_config.json
LogFile: /var/log/vmware/vmdk_ops.log
LogLevel: INFO
=== Authorization Config DB: 
DB_LocalPath: N/A
DB_Mode: NotConfigured (no local DB, no symlink to shared DB)
DB_SharedLocation: N/A
```
steps to reproduce:
1. Make sure you have clean environment (fresh setup is recommended OR remove dockvol/authdb etc)
2. install vDVS driver (VIB)
3. invoke `esxcli storage guestvol status` to make sure vmdkops service is running fine
4. invoke `esxcli storage guestvol config init --datastore=<sharedDS_name>`

Observe the following error cause.

**Expected behavior**: MultiNode config db should be created without any problem.

```
root@sc-rdops-vm17-dhcp-15-182:~] esxcli storage guestvol config init --datastore="sharedVmfs-0"
Got no data from process: LANG=en_US.UTF-8 /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py --output-format=xml config init  --datastore='sharedVmfs-0'  
```

```
[root@sc-rdops-vm17-dhcp-15-182:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py --output-format=xml config init  --datastore='sharedVmfs-0'
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/Python/auth_data.py", line 640, in __connect
    self.conn = sqlite3.connect(self.db_path)
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 1478, in <module>
    main()
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 72, in main
    if args.func(args) != None:
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 1325, in config_init
    err = auth.new_db()
  File "/usr/lib/vmware/vmdkops/Python/auth_data.py", line 761, in new_db
    self.__connect()
  File "/usr/lib/vmware/vmdkops/Python/auth_data.py", line 643, in __connect
    raise DbConnectionError(self.db_path)
auth_data.DbConnectionError: DB connection error at /vmfs/volumes/sharedVmfs-0/dockvols/vmdkops_config.db
```

**Comment by shuklanirdesh82** [comment]
This is related with Cross ESX multi tenancy so not adding `mustfix` keyword. 

Workaround is to create `dockvols` directory at `/vmfs/volumes/<sharedDS_Name>/` helps to avoid reported issue. 

@tusharnt @govint : what do you think? If you think we should address by kubecon release then `mustfix` kw should be added.

**Comment by govint** [comment]
No, this needs to be addressed post the upcoming release and possibly rethink the use of a DB itself.
