### ISSUE TITLE
Detach failure during VM shutdown brings ESX service down

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#381]
Setup: Photon RC, TP2 release

Steps to repro;
1. Create volume: `docker volume create -d vmdk --name tv1`
2. Run container: `docker run -d -it --restart="always" -v tv1:/data busybox`
3. Shudown VM from ESX UI
4. Noticed Server crash and disk tv1.vmdk remains attached to VM

```
05/20/16 18:47:04 2896177 [INFO   ] *** detachVMDK: /vmfs/volumes/4bad174b-b67f5cfc-2fc6-0026b966a303/dockvols/tv1.vmdk from Photon1 VM uuid = 564db5e5-a5a9-5d76-b349-70cd1326d9fd
05/20/16 18:47:04 2896177 [ERROR  ] (vim.fault.InvalidState) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'The operation is not allowed in the current state.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 691, in main
    handleVmciRequests()
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 672, in handleVmciRequests
    details["Name"], opts)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 370, in executeRequest
    response = detachVMDK(vmdk_path, vm_name)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 320, in detachVMDK
    return disk_detach(vmdk_path, vm)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 613, in disk_detach
    wait_for_tasks(si, [vm.ReconfigVM_Task(spec=spec)])
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 764, in wait_for_tasks
    raise task.info.error
vim.fault.InvalidState: (vim.fault.InvalidState) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'The operation is not allowed in the current state.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
05/20/16 18:47:05 2898676 [INFO   ] === Starting vmdkops service ===
```
From Hostd log
```
ager opID=22e3cf71 user=dcui:dvolplug] Task Created : haTask-4-vim.VirtualMachine.reconfigure-539009485
s/volumes/4bad174b-b67f5cfc-2fc6-0026b966a303/Photon1/Photon1.vmx opID=22e3cf71 user=dcui:dvolplug] Invalid transition requested (VM_STATE_ON_SHUTTING_DOWN -> VM_STATE_RECONFIGURING): Invalid state
mfs/volumes/4bad174b-b67f5cfc-2fc6-0026b966a303/Photon1/Photon1.vmx opID=22e3cf71 user=dcui:dvolplug] Failed to start Reconfiguring: vim.fault.InvalidState
2e3cf71 user=dcui:dvolplug] AdapterServer caught exception: vim.fault.InvalidState
```

**Comment by govint** [comment]
PR #433

**Comment by msterin** [comment]
An update: 
Hiding the exception would not fix the actual bug - which is as follows: 
* VM is put in "shutting down" mode by ESX operation. 
* Vm reboot causes Docker to unmount and detach a volume, which sends 'detach' request to ESX
* ESX fails the reconfig request because VM is in "shutting down" state.
  * python service crashes - this **can** be fixed by catching the exception
  * Volume stays attached - which is the key issue and **cannot** be fixed by catching the exception

End result - the VMDK volume stays attached after VM reboot.
