### ISSUE TITLE
Intermittent Server crash with "Connection reset by peer" on ESX

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#382]
I intermittently see server restarts with "[Errno 104] Connection reset by peer". I don't have exact steps but in this particular case, here was sequence:

1. Create volume: docker volume create -d vmdk --name tv1
2. Run container: docker run -d -it --restart="always" -v tv1:/data busybox
3. Shudown VM from ESX UI
4. Noticed Server crash and disk tv1.vmdk remains attached to VM (#381)
5. Power on VM
6. Docker attempts to restart container, Sends mount/attach for tv1.vmdk
7. Server restarts with following error and docker fails to start container.

```
05/20/16 18:47:05 2898676 [INFO   ] === Starting vmdkops service ===
05/20/16 18:55:38 2898676 [ERROR  ] [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 691, in main
    handleVmciRequests()
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 672, in handleVmciRequests
    details["Name"], opts)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 368, in executeRequest
    response = attachVMDK(vmdk_path, vm_name)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 309, in attachVMDK
    vm = findVmByName(vm_name)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 296, in findVmByName
    vm = FindChild(GetVmFolder(), vm_name)
  File "/build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVim/invt.py", line 77, in GetVmFolder
  File "/build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVim/invt.py", line 42, in GetDatacenter
  File "/build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 543, in <lambda>
  File "/build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 352, in _InvokeMethod
  File "/build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1241, in InvokeMethod
  File "/build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys-boot/lib/python2.7/httplib.py", line 1073, in getresponse
  File "/build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys-boot/lib/python2.7/httplib.py", line 415, in begin
  File "/build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys-boot/lib/python2.7/httplib.py", line 371, in _read_status
  File "/build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys-boot/lib/python2.7/socket.py", line 476, in readline
  File "/build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys-boot/lib/python2.7/ssl.py", line 714, in recv
  File "/build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys-boot/lib/python2.7/ssl.py", line 608, in read
error: [Errno 104] Connection reset by peer
```

**Comment by pdhamdhere** [comment]
```
while :
do
   echo "creating volume"
   docker volume create -d vmdk --name=myvol1 -o size=2gb
   docker run --rm -it -v myvol1:/data busybox sh -c 'touch /data/test; ls -l /data/'
   echo "removing volume"
   docker volume rm myvol1
   echo "press ctrl c to stop"
   sleep 1
done
```

Ran above script from 2 different docker host and didnt see any issues. Earlier it was 100% reproducible. Closing.
