### ISSUE TITLE
Build both 32 and 64-bit versions of the vmci server library and install those on the server.

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#482]
Issue #480 is being fixed and code is ready for that. But the server won't start as the vmci_srv library is 32-bit. With Python 3.5.1 we need libs to be 64-bit. The plugin build must build both 32 and 64-bit libraries and install those on the host.

06/22/16 12:59:42 1000071179 [MainThread] [INFO   ] === Starting vmdkops service ====
06/22/16 12:59:42 1000071179 [MainThread] [WARNING] Failed to load disk library, retrying <----- if 32-bit disklib load fails then we try using the 64-bit library, same needs to be done for vmci_srv.so too.

06/22/16 12:59:42 1000071179 [MainThread] [ERROR  ] /usr/lib/vmware/vmdkops/lib/libvmci_srv.so: wrong ELF class: ELFCLASS32
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 846, in main
    handleVmciRequests(port)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 747, in handleVmciRequests
    lib = CDLL(os.path.join(LIB_LOC, "libvmci_srv.so"), use_errno=True)
  File "/dbc/blr-dbc401/tthirumal/cbrc-pr/main-stage/bora/build/esx/obj/vmvisor/sys-boot/lib64/python3.5/ctypes/__init__.py", line 347, in __init__
OSError: /usr/lib/vmware/vmdkops/lib/libvmci_srv.so: wrong ELF class: ELFCLASS32

**Comment by govint** [comment]
Addressed via #480
