### ISSUE TITLE
Tests failing with "Out of Resources" error on CI

### ISSUE THREAD

**Issue by andrewjstone** [vmware/docker-volume-vsphere#490]
Running unit tests in /tmp/vmdk_ops_unittest11949/vmdk_ops_test.py...
....FF.
======================================================================
FAIL: testPolicy (__main__.VmdkCreateRemoveTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/vmdk_ops_unittest11949/vmdk_ops_test.py", line 161, in testPolicy
    self.assertEqual(err == None, unit[2], err)
AssertionError: {u'Error': 'Failed to create /vmfs/volumes/vsan:5220b6f4208d15c5-22eacf2d7f134e1c/dockvols/vol_UnitTest_Create0.vmdk. Failed to create virtual disk: Out of resources (469766731).\n'}

======================================================================
FAIL: testPolicyUpdate (__main__.VmdkCreateRemoveTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/vmdk_ops_unittest11949/vmdk_ops_test.py", line 120, in testPolicyUpdate
    self.assertEqual(err, None, err)
AssertionError: {u'Error': 'Failed to create /vmfs/volumes/vsan:5220b6f4208d15c5-22eacf2d7f134e1c/dockvols/vol_UnitTest_Create.vmdk. Failed to create virtual disk: Out of resources (469766731).\n'}

----------------------------------------------------------------------

**Comment by andrewjstone** [comment]
The logs here show the errors: https://ci.vmware.run/vmware/docker-volume-vsphere/690

**Comment by andrewjstone** [comment]
Dup of #489. Closing.
