### ISSUE TITLE
Failing Tests do not cause CI to fail

### ISSUE THREAD

**Issue by andrewjstone** [vmware/docker-volume-vsphere#491]
The test failure shown in #490 can still result in CI passes. My guess is that whatever command is running the tests is not consuming the error code somehow.

**Comment by andrewjstone** [comment]
Error with success shown here: https://ci.vmware.run/vmware/docker-volume-vsphere/642

**Comment by andrewjstone** [comment]
I reproduced this locally. Investigating.

**Comment by andrewjstone** [comment]
Running directly on ESX, there is no error returned to the shell on the failing test from python

```
[root@localhost:/tmp/vmdk_ops_unittest] python vmdk_ops_test.py
ss..Es.
======================================================================
ERROR: testPolicy (__main__.VmdkCreateRemoveTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "vmdk_ops_test.py", line 152, in testPolicy
    vmdk_path = vmdk_utils.get_vmdk_path(path,vol_name)
  File "/usr/lib/vmware/vmdkops/Python/vmdk_utils.py", line 68, in get_vmdk_path
    return os.path.join(path, "{0}.vmdk".format(vol_name))
  File "/build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys-boot/lib/python2.7/posixpath.py", line 77, in join
AttributeError: 'NoneType' object has no attribute 'endswith'

----------------------------------------------------------------------
Ran 7 tests in 0.491s

FAILED (errors=1, skipped=3)
[root@localhost:/tmp/vmdk_ops_unittest] echo $?
0
```
