### ISSUE TITLE
Mock ESX no longer works

### ISSUE THREAD

**Issue by andrewjstone** [vmware/docker-volume-vsphere#518]
This can be shown with the following commands on a VM:

term 1
```bash
sudo service docker-volume-vsphere stop
sudo /usr/local/bin/docker-volume-vsphere -port 1019 --mock_esx
```

term 2
```bash
ajs@ajs-virtual-machine:~$ docker volume create -d vmdk --name myvol
myvol
ajs@ajs-virtual-machine:~$ docker volume ls
DRIVER              VOLUME NAME
docker run --rm -it -v myvol:/mnt/myvol busybox
docker: Error response from daemon: Post http://%2Frun%2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.Mount: http: ContentLength=17 with Body length 0.
```

The mount produces this crash: 
```
2016/07/08 14:54:49 http: panic serving @: assignment to entry in nil map
goroutine 9 [running]:
net/http.(*conn).serve.func1(0xc820070b80)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x7f8220, 0xc8200e82d0)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
main.(*vmdkDriver).Mount(0xc820053530, 0xc8200e8268, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/vmware/docker-volume-vsphere/vmdk_plugin/plugin.go:205 +0x373
github.com/vmware/docker-volume-vsphere/vendor/github.com/docker/go-plugins-helpers/volume.(*Handler).initMux.func6(0xc8200e8268, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/vmware/docker-volume-vsphere/vendor/github.com/docker/go-plugins-helpers/volume/api.go:91 +0xa6
github.com/vmware/docker-volume-vsphere/vendor/github.com/docker/go-plugins-helpers/volume.(*Handler).handle.func1(0x7fcf72383d38, 0xc8200e2c30, 0xc82000c9a0)
	/go/src/github.com/vmware/docker-volume-vsphere/vendor/github.com/docker/go-plugins-helpers/volume/api.go:106 +0xd8
net/http.HandlerFunc.ServeHTTP(0xc820013820, 0x7fcf72383d38, 0xc8200e2c30, 0xc82000c9a0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820053590, 0x7fcf72383d38, 0xc8200e2c30, 0xc82000c9a0)
	/usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820070680, 0x7fcf72383d38, 0xc8200e2c30, 0xc82000c9a0)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820070b80)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
```

This appears to be due to a change made in this PR: https://github.com/vmware/docker-volume-vsphere/pull/224

The problem is that the loopback devices that are created are no longer mounted. There needs to be conditional code for the mock scenario as it was not considered with this change.

The main line in question is: https://github.com/vmware/docker-volume-vsphere/pull/224/files#diff-70e973989f81df39acd35aa417b206bcL90

Note the original PR for mock_esx: https://github.com/vmware/docker-volume-vsphere/commit/3e86cbb3ed3b01a498249fefe20c1d0dfc4e595d#diff-f6c6bb8a6ec40b9f63d107bc7070f708R32

When using the original PR code:

term 1
```bash
git checkout 3e86cbb3ed3b01a498249fefe20c1d0dfc4e595d
./build.sh
ajs@ajs-virtual-machine:~/go/src/github.com/vmware/docker-volume-vsphere$ sudo ./bin/docker-vmdk-plugin --mock_esx
2016/07/08 15:01:49 VMDK Volume Driver v0.2 (port: 15000, mock_esx: true)
2016/07/08 15:01:49 Going into ServeUnix - Listening on Unix socket: %s/run/docker/plugins/vmdk.sock
2016/07/08 15:07:01 Running Mock Cmd create
2016/07/08 15:07:04 Running Mock Cmd list
2016/07/08 15:07:32 Mounting volume hello on /mnt/vmdk/hello
2016/07/08 15:07:32 Running Mock Cmd attach
2016/07/08 15:07:32 Mounting /dev/loop1002 for label /mnt/vmdk/hello
```

term 1
```bash
js@ajs-virtual-machine:~$ docker volume create --driver=vmdk --name=hello
hello
ajs@ajs-virtual-machine:~$ docker volume ls
DRIVER              VOLUME NAME
vmdk                hello
ajs@ajs-virtual-machine:~$ docker run --rm -it -v hello:/mnt/myvol busybox
/ #
```

Once fixed we should add a test that exercises this code path. I believe that there is already an issue for that. It doesn't have to be part of the PR for this fix necessariily.

Assigning to @govint since his commit broke it.

**Comment by govint** [comment]
mockesx seems to be not tested in any of the tests looks like as this change was made some time back. Since I do have a real ESX I don't use mock esx at all either. Do we want to retain mockesx for long. I'll this fix this anyway

**Comment by govint** [comment]
mock-esx Get() method returns OK error which means docker isn't even issuing create to the volume plugin. I don't see any files getting created in the folder where mock-esx keeps its volumes.

Have fixed the issue but found this in testing.

**Comment by govint** [comment]
Another one, in mock mode the client plugin isn't creating the ref counts map. Why? Only esx is being mock'ed up. Fixing.

**Comment by govint** [comment]
Works after #540
