### ISSUE TITLE
docker volume inspect command cause vmdkops service crash when the volume name is unicode character

### ISSUE THREAD

**Issue by lipingxue** [vmware/docker-volume-vsphere#575]
In docker, run "docker volume inspect" command with a volume name which is an unicode character:

```
root@photon-machine [ ~ ]# docker volume inspect 你
[]
Error: No such volume: 你

```

See the following vmdk_ops.log:

```
tail -f /var/log/vmware/vmdk_ops.log
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 560, in executeRequest
    vmdk_path = vmdk_utils.get_vmdk_path(path, vol_name)
  File "/usr/lib/vmware/vmdkops/Python/vmdk_utils.py", line 92, in get_vmdk_path
    delta_disks = glob.glob("{0}/{1}{2}".format(path, vol_name, SNAP_SUFFIX_GLOB))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u4f60' in position 0: ordinal not in range(128)
08/05/16 17:14:45 53134 [MainThread] [INFO   ] === Starting vmdkops service ====
08/05/16 17:14:45 53134 [MainThread] [INFO   ] Loading VMCI server lib.
08/05/16 17:15:37 53134 [photon] [INFO   ] executeRequest 'get' completed with ret={u'Error': 'Volume NewV not found (file: /vmfs/volumes/datastore1/dockvols/NewV.vmdk)'}
08/05/16 17:15:37 53134 [photon] [INFO   ] *** createVMDK: /vmfs/volumes/datastore1/dockvols/NewV.vmdk opts = {u'size': u'10gb'}
08/05/16 17:15:37 53134 [photon] [INFO   ] executeRequest 'create' completed with ret=None
08/05/16 17:29:20 53134 [photon] [ERROR  ] 'ascii' codec can't encode character u'\u4f60' in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1001, in main
    handleVmciRequests(port)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 958, in handleVmciRequests
    opts=opts)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 560, in executeRequest
    vmdk_path = vmdk_utils.get_vmdk_path(path, vol_name)
  File "/usr/lib/vmware/vmdkops/Python/vmdk_utils.py", line 92, in get_vmdk_path
    delta_disks = glob.glob("{0}/{1}{2}".format(path, vol_name, SNAP_SUFFIX_GLOB))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u4f60' in position 0: ordinal not in range(128)
08/05/16 17:29:20 53754 [MainThread] [INFO   ] === Starting vmdkops service ====
08/05/16 17:29:20 53754 [MainThread] [INFO   ] Loading VMCI server lib.
```

After crash, the vmdkops service restart automatically.

**Comment by govint** [comment]
Its good to fix this in the plugin server, but IOW how docker passed
invalid input. Please raise an issue on docker also if the issue is failing
on docker local volumes.

**Comment by shaominchen** [comment]
Hi Shahzeb, can you take a look at this issue?

**Comment by pshahzeb** [comment]
Sure. I will get started on this.
