### ISSUE TITLE
Admin cli without any options returns error

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#585]
When run as below the admin CLI returns an error. Ideally it should be printing the help message and exit.

Admin CLI with "-h" option:

python /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py -h
usage: vmdkops_admin.py [-h] {role,ls,status,policy} ...

Manage VMDK Volumes

positional arguments:
  {role,ls,status,policy}
    role                Administer and monitor volume access control
    ls                  List volumes
    status              Show the status of the vmdk_ops service
    policy              Configure and display storage policy information

optional arguments:
  -h, --help            show this help message and exit

Admin CLI without any options:
python /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 583, in <module>
    main()
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 39, in main
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'

**Comment by govint** [comment]
Fixed by #593

**Comment by govint** [comment]
Fixed via #593
