### ISSUE TITLE
vmdk admin cli  'ls' command errors with Python 3.5.1

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#590]
The subprocess.checkoutput() returns an encoded byte output (unlike a string in 2.7). Needs to be decoded  before using.

python ./vmdkops_admin.py ls
b'Capacity bytes: 104857600 \nUsed bytes: 14680064 \nUnshared bytes: 14680064 \n'
Traceback (most recent call last):
  File "./vmdkops_admin.py", line 606, in <module>
    main()
  File "./vmdkops_admin.py", line 39, in main
    args.func(args)
  File "./vmdkops_admin.py", line 348, in ls
    rows = generate_ls_rows()
  File "./vmdkops_admin.py", line 384, in generate_ls_rows
    size_info = get_vmdk_size_info(path)
  File "./vmdkops_admin.py", line 443, in get_vmdk_size_info
    lines = output.split('\n')
TypeError: a bytes-like object is required, not 'str'

**Comment by govint** [comment]
Closed via #591
