### ISSUE TITLE
typo in vmdkops_admin.py set  throws an exception

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#609]
On master,  reproducable - a mistake in admin 'set' command throws: 
```
root@sc2-rdops-vm02-dhcp-90-23:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py set --volume what@datastore1  --options acces=read-only
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 638, in <module>
    main()
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 40, in main
    args.func(args)
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 566, in set_vol_opts
    set_ok = vmdk_ops.set_vol_opts(args.volume, args.options) 
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1042, in set_vol_opts
    raise ValidationError(msg)
vmdk_ops.ValidationError: "Invalid options: ['acces'] \nOptions that can be edited: ['access', 'attach-as']"

```

@Govint  - assigning to you since you where the last who touched set_vol_opts:1042

**Comment by govint** [comment]
Ah, its working as expected "access" is supported, "acces" isn't access :-))

**Comment by andrewjstone** [comment]
No, this is a user facing CLI. Errors should not just be uncaught exceptions. They should look more like this: 
```
root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py lsadfadf
usage: vmdkops_admin.py [-h] {policy,status,set,role,ls} ...
vmdkops_admin.py: error: invalid choice: 'lsadfadf' (choose from 'policy', 'status', 'set', 'role', 'ls')
```

**Comment by msterin** [comment]
Exactly - it should be an error msg like in all other places, not a backtrace
