### ISSUE TITLE
Tests seem to fail but build passes

### ISSUE THREAD

**Issue by kerneltime** [vmware/docker-volume-vsphere#644]
This https://ci.vmware.run/vmware/docker-volume-vsphere/1500 is the most recent build of master and it passed but upon inspection of logs it looks like there was a failure.
If this is a negative test and is expected to fail, let's print that before the test.

```
OK
Running unit tests in /tmp/vmdk_ops_unittest22639/vmdkops_admin_test.py...
.ERROR:root:Failed to decode meta-data for /vmfs/volumes/575db611-d1ad6cf9-0c74-000c29e3609e/dockvols/volP10.vmdk
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/Python/kvESX.py", line 249, in load
    return json.loads(kv_str)
  File "/build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys-boot/lib/python2.7/json/__init__.py", line 338, in loads
  File "/build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys-boot/lib/python2.7/json/decoder.py", line 366, in decode
  File "/build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys-boot/lib/python2.7/json/decoder.py", line 384, in raw_decode
ValueError: No JSON object could be decoded
........................
```

**Comment by brunotm** [comment]
@kerneltime 
This is a leftover from a previous CI run that failed with the kv - issue #626, which also affects the master branch.
Needs manual cleanup, the current code (removeVMDK) will fail deleting this volume.

**Comment by kerneltime** [comment]
Hmm.. there is still the question of why the unit test is failing and the build is passing..

**Comment by brunotm** [comment]
There's more info and a workaround in #612

**Comment by msterin** [comment]
@kerneltime  - do we still have this Issue ? It looks like the root cause was already addressed...

**Comment by shuklanirdesh82** [comment]
@kerneltime / @msterin : can this be closed? 

FYI: We have never experienced the reported issue in past 2 months.

//CC @pdhamdhere
