### ISSUE TITLE
Shared volume not working in Swarm mode.

### ISSUE THREAD

**Issue by MattAtTTU** [vmware/docker-volume-vsphere#671]
Testing VMWare volume on shared datastore with multiple Swarm nodes and containers using a single volume. 

Test procedure:

1.  Create VMDK volume on shares DS. (Works)
2.  Create Swarm service with volume mounted within. (Wprks)
3.  Make change to shared volume through Swarm service. (Works)
4.  Create second Swarm service with volume mounted within. (NOT WORKING)

When the second Swarm service is created, it will not full start.  Swarm continues to try and restart is on separate node form the first service and it will never start. 

The docker-volume-vsphere.log on the Swarm node shows the following error each time the service attempts to start:

```
2016-11-01 14:23:21.02430126 -0500 CDT [INFO] Mounting volume name="MyTestVol@COMP_Ent_VMWare_Flocker_01" 
2016-11-01 14:23:21.300267399 -0500 CDT [ERROR] Failed to mount name="MyTestVol@COMP_Ent_VMWare_Flocker_01" error="Server returned an error: AttributeError(\"'NoneType' object has no attribute 'config'\",)" 
2016-11-01 14:23:21.475005978 -0500 CDT [INFO] Unmounting Volume name="MyTestVol@COMP_Ent_VMWare_Flocker_01" 
2016-11-01 14:23:21.475089178 -0500 CDT [ERROR] Failed to unmount volume. Now trying to detach... error="invalid argument" mountpoint="/mnt/vmdk/MyTestVol@COMP_Ent_VMWare_Flocker_01" 
2016-11-01 14:23:22.138530245 -0500 CDT [ERROR] Failed to unmount error="*** Detach failed: disk=/vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk not found. VM=423cd261-1f20-dd44-a26a-f415d87b406d" name="MyTestVol@COMP_Ent_VMWare_Flocker_01"
```

The vmdk_ops.log on the VMWare host shows the following error each time the service attempts to start:

```
11/01/16 19:23:21 14635822 [entswarmapp2-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] *** attachVMDK: /vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk to entswarmapp2 VM uuid = 423cd261-1f20-dd44-a26a-f415d87b406d
11/01/16 19:23:21 14635822 [entswarmapp2-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] Attaching /vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk as independent_persistent
11/01/16 19:23:21 14635822 [entswarmapp2-MyTestVol@COMP_Ent_VMWare_Flocker_01] [ERROR  ] Unhandled Exception:
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1205, in execRequestThread
    opts=opts)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 614, in executeRequest
    response = attachVMDK(vmdk_path, vm_uuid)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 464, in attachVMDK
    return disk_attach(vmdk_path, vm)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 896, in disk_attach
    ret_err = handle_stale_attach(vmdk_path, kv_uuid)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 784, in handle_stale_attach
    cur_vm = findVmByUuid(kv_uuid)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 455, in findVmByUuid
    logging.info("Found VM name=%s, id=%s ", vm.config.name, vm_uuid)
AttributeError: 'NoneType' object has no attribute 'config'
```

I've searched through other issues and can't find where/if this has been tested.  The documentation indicated volumes can be shared, but has this been tested across Swarm nodes?

**Comment by pdhamdhere** [comment]
@MattAtTTU vSphere Docker Volume can NOT be shared between 2 Docker Nodes (VMs). Containers running on same node can share vSphere docker volume. Since docker volumes are formatted with local file system, 2 independent nodes writing to local FS can lead to unintended consequences. We would love to hear your use-case for sharing same volume across multiple nodes.

Regarding stack trace, looks like a bug that we should fix and code should report an appropriate error - "Volume already in use by XXX node". CC/ @govint

**Comment by MattAtTTU** [comment]
Thank you for the explanation.  The use case is simply to allow containers to share a volume while not restricting Docker Swarm to the nodes it can use to run said containers.  By default, the tasks are scheduled on whatever Swarm node has less resources.  We must override that and manually place containers sharing storage on the same Swarm node with this behavior.

At any rate, I understand why the volumes cannot be shared and I suspected this may be the case.  Thank you again for the explanation.

**Comment by kerneltime** [comment]
@MattAtTTU If you don't mind we will be reaching out to you via email to learn a bit more about your environment.

**Comment by govint** [comment]
This behavior was identified in #601.

Regarding the stack in the plugin server logs, @MattAtTTU  can you do this:

1. Post the server logs from the ESX server. I'd like to see which VM attached the volume ahead of the one that failed the mount.

2. Do a docker volume inspect <volume name> when the error happens (and the service is still running on the other node)

**Comment by govint** [comment]
Also @MattAtTTU can you say if you are running with the current version of the server code in the repository (threaded server version).

**Comment by MattAtTTU** [comment]
Yes, I am running with the current version of the code (October Release).

1.  Server logs from three hosts are below.  We have three swarm nodes in total (manager and two app nodes).  The manager is capable of hosting containers and sometimes does, as was the case with the first test container deployed in this test. 

Host1 with node that can't mount volume:
```
11/02/16 13:45:41 14635822 [entswarmapp2-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] Attaching /vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk as independent_persistent
11/02/16 13:45:42 14635822 [entswarmapp2-MyTestVol@COMP_Ent_VMWare_Flocker_01] [ERROR  ] Unhandled Exception:
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1205, in execRequestThread
    opts=opts)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 614, in executeRequest
    response = attachVMDK(vmdk_path, vm_uuid)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 464, in attachVMDK
    return disk_attach(vmdk_path, vm)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 896, in disk_attach
    ret_err = handle_stale_attach(vmdk_path, kv_uuid)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 784, in handle_stale_attach
    cur_vm = findVmByUuid(kv_uuid)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 455, in findVmByUuid
    logging.info("Found VM name=%s, id=%s ", vm.config.name, vm_uuid)
AttributeError: 'NoneType' object has no attribute 'config'
11/02/16 13:45:42 14635822 [entswarmapp2-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] *** detachVMDK: /vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk from entswarmapp2 VM uuid = 423cd261-1f20-dd44-a26a-f415d87b406d
11/02/16 13:45:42 14635822 [entswarmapp2-MyTestVol@COMP_Ent_VMWare_Flocker_01] [WARNING] *** Detach failed: disk=/vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk not found. VM=423cd261-1f20-dd44-a26a-f415d87b406d
11/02/16 13:45:42 14635822 [entswarmapp2-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] executeRequest 'detach' completed with ret={u'Error': '*** Detach failed: disk=/vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk not found. VM=423cd261-1f20-dd44-a26a-f415d87b406d'}
11/02/16 13:45:54 14635822 [entswarmapp2-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] executeRequest 'get' completed with ret={'status': u'attached', 'attached to VM': u'entswarmmgr1', 'created by VM': u'entswarmmgr1', 'capacity': {'allocated': '307MB', 'size': '10GB'}, 'created': u'Wed Nov  2 13:41:30 2016', 'fstype': u'ext4', 'access': 'read-write', 'attach-as': 'independent_persistent', 'diskformat': u'thin', 'datastore': u'COMP_Ent_VMWare_Flocker_01'}
11/02/16 13:45:54 14635822 [entswarmapp2-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] *** attachVMDK: /vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk to entswarmapp2 VM uuid = 423cd261-1f20-dd44-a26a-f415d87b406d
11/02/16 13:45:54 14635822 [entswarmapp2-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] Attaching /vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk as independent_persistent
11/02/16 13:45:54 14635822 [entswarmapp2-MyTestVol@COMP_Ent_VMWare_Flocker_01] [ERROR  ] Unhandled Exception:
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1205, in execRequestThread
    opts=opts)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 614, in executeRequest
    response = attachVMDK(vmdk_path, vm_uuid)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 464, in attachVMDK
    return disk_attach(vmdk_path, vm)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 896, in disk_attach
    ret_err = handle_stale_attach(vmdk_path, kv_uuid)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 784, in handle_stale_attach
    cur_vm = findVmByUuid(kv_uuid)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 455, in findVmByUuid
    logging.info("Found VM name=%s, id=%s ", vm.config.name, vm_uuid)
AttributeError: 'NoneType' object has no attribute 'config'
11/02/16 13:45:54 14635822 [entswarmapp2-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] *** detachVMDK: /vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk from entswarmapp2 VM uuid = 423cd261-1f20-dd44-a26a-f415d87b406d
11/02/16 13:45:55 14635822 [entswarmapp2-MyTestVol@COMP_Ent_VMWare_Flocker_01] [WARNING] *** Detach failed: disk=/vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk not found. VM=423cd261-1f20-dd44-a26a-f415d87b406d
11/02/16 13:45:55 14635822 [entswarmapp2-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] executeRequest 'detach' completed with ret={u'Error': '*** Detach failed: disk=/vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk not found. VM=423cd261-1f20-dd44-a26a-f415d87b406d'}
```

Host2 with node that can't mount volume:
```
11/02/16 13:45:48 14693453 [entswarmapp1-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] *** attachVMDK: /vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk to entswarmapp1 VM uuid = 423c6351-f4a1-be09-7975-85269eebdd96
11/02/16 13:45:48 14693453 [entswarmapp1-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] Attaching /vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk as independent_persistent
11/02/16 13:45:48 14693453 [entswarmapp1-MyTestVol@COMP_Ent_VMWare_Flocker_01] [ERROR  ] Unhandled Exception:
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1205, in execRequestThread
    opts=opts)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 614, in executeRequest
    response = attachVMDK(vmdk_path, vm_uuid)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 464, in attachVMDK
    return disk_attach(vmdk_path, vm)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 896, in disk_attach
    ret_err = handle_stale_attach(vmdk_path, kv_uuid)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 784, in handle_stale_attach
    cur_vm = findVmByUuid(kv_uuid)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 455, in findVmByUuid
    logging.info("Found VM name=%s, id=%s ", vm.config.name, vm_uuid)
AttributeError: 'NoneType' object has no attribute 'config'
11/02/16 13:45:48 14693453 [entswarmapp1-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] executeRequest 'get' completed with ret={'status': u'attached', 'attached to VM': u'entswarmmgr1', 'created by VM': u'entswarmmgr1', 'capacity': {'allocated': '307MB', 'size': '10GB'}, 'created': u'Wed Nov  2 13:41:30 2016', 'fstype': u'ext4', 'access': 'read-write', 'attach-as': 'independent_persistent', 'diskformat': u'thin', 'datastore': u'COMP_Ent_VMWare_Flocker_01'}
11/02/16 13:45:48 14693453 [entswarmapp1-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] *** detachVMDK: /vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk from entswarmapp1 VM uuid = 423c6351-f4a1-be09-7975-85269eebdd96
11/02/16 13:45:48 14693453 [entswarmapp1-MyTestVol@COMP_Ent_VMWare_Flocker_01] [WARNING] *** Detach failed: disk=/vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk not found. VM=423c6351-f4a1-be09-7975-85269eebdd96
11/02/16 13:45:48 14693453 [entswarmapp1-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] executeRequest 'detach' completed with ret={u'Error': '*** Detach failed: disk=/vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk not found. VM=423c6351-f4a1-be09-7975-85269eebdd96'}
```

Host running first container created with volume mounted successfully:
```
11/02/16 13:42:59 3161819 [entswarmmgr1-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] *** attachVMDK: /vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk to entswarmmgr1 VM uuid = 423c971f-ca16-26b7-a097-3a10186997f3
11/02/16 13:42:59 3161819 [entswarmmgr1-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] Attaching /vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk as independent_persistent
11/02/16 13:43:00 3161819 [entswarmmgr1-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] Disk /vmfs/volumes/COMP_Ent_VMWare_Flocker_01/dockvols/MyTestVol.vmdk successfully attached. controller pci_slot_number=192, disk_slot=0
11/02/16 13:43:00 3161819 [entswarmmgr1-MyTestVol@COMP_Ent_VMWare_Flocker_01] [INFO   ] executeRequest 'attach' completed with ret={'ControllerPciSlotNumber': '192', 'Unit': '0'}
11/02/16 13:44:05 3161819 [entswarmmgr1-socket7] [INFO   ] executeRequest 'list' completed with ret=[{u'Attributes': {}, u'Name': 'testdomain@COMP_Ent_VMWare_Flocker_01'}, {u'Attributes': {}, u'Name': 'MyTestVol@COMP_Ent_VMWare_Flocker_01'}]
```

2.  Here is the output of the volume inspect on one


[Host2-vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/566722/Host2-vmdk_ops.txt)
[Host3-vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/566724/Host3-vmdk_ops.txt)
[Host1-vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/566723/Host1-vmdk_ops.txt)



 node that was attempting to start the second container that will never fully start, due to the volume already being mounted on another node.

```
 [
    {
        "Name": "MyTestVol@COMP_Ent_VMWare_Flocker_01",
        "Driver": "vmdk",
        "Mountpoint": "/mnt/vmdk/MyTestVol@COMP_Ent_VMWare_Flocker_01",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "attached to VM": "entswarmmgr1",
            "capacity": {
                "allocated": "307MB",
                "size": "10GB"
            },
            "created": "Wed Nov  2 13:41:30 2016",
            "created by VM": "entswarmmgr1",
            "datastore": "COMP_Ent_VMWare_Flocker_01",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "attached"
        },
        "Labels": {},
        "Scope": "global"
    }
]
```

**Comment by govint** [comment]
@MattAtTTU, thanks for the details, whats happening is that we have the volume attached to a VM on one host but when we try to look for a VM with that UUID on another host we don't find it because the VM thats attached the volume is registered on the other host and hence the stack trace.

Yes, needs a code fix to check whether a VM was really found with the UUID on the host. And perhaps documentation to make it clear that services on multiple hosts can't share the same volume.

**Comment by govint** [comment]
@MattAtTTU Can this issue be closed as there are no code changes, the feature is working as expected and shared volumes aren't supported at this time. The stack seen in the traces won't happen with the current code.

**Comment by MattAtTTU** [comment]
Yes, this can be closed.  Closing.
